### ISSUE TITLE
Line-by-line profiling?

### ISSUE THREAD

**Issue by anntzer** [bdarnell/plop#27]
It is possible to introspect the current line number in a CPython frame (`f_lineno`), and recording this information can obviously help the optimization of large-ish functions (see https://github.com/rkern/line_profiler for an instrumenting profiler with the same approach).

Any chance this capability can be added to plop?  (crossposted as vmprof/vmprof-python#54)

**Comment by bdarnell** [comment]
Hmm, that's a good question. I don't know why plop uses `frame.f_code.co_firstlineno` instead of `frame.f_lineno`. The latter seems much more useful. Does it work if you replace `code.co_firstlineno` with `frame.f_lineno` in https://github.com/bdarnell/plop/blob/453ff65538de4f327717112a043caab2de847930/plop/collector.py#L67?

**Comment by anntzer** [comment]
That "seems to work", but I think a line-by-line annotation output is needed to make this truly useful.  (I know I'm asking for a lot...)

**Comment by bdarnell** [comment]
Ah, so you want a different output format? That's different. Once the correct information is captured, you should be able to write a tool that can parse plop's output and produce this annotation. However, I'm not sure that annotated source is the best format for a sample-based profile; the output will be pretty sparse.

**Comment by anntzer** [comment]
It'll probably depend on the sampling rate and to what extent we have a severe bottleneck... in any case the only way to know is (...for me, I guess :p) to write it.
